theme: jekyll-theme-slate

title: renqHIT

baseurl: /
mkardown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

gems:
  - jekyll-paginate
  - jekyll-sitemap
  
